### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by XFizzer** [fengberd/FDevTools#8]
08.07 16:45:17 [Server] INFO 	at moe.berd.FDevTools.Main.checkCompiler(Main.java:196)
08.07 16:45:17 [Server] INFO at java.lang.ClassLoader.loadClass(Unknown Source)
08.07 16:45:17 [Server] INFO at java.lang.ClassLoader.loadClass(Unknown Source)
08.07 16:45:17 [Server] INFO at java.net.URLClassLoader.findClass(Unknown Source)
08.07 16:45:17 [Server] INFO 16:45:17 [INFO] [FDevTools] Compiler not found,loading third-party compiler...
08.07 16:45:17 [Server] INFO java.lang.ClassNotFoundException: com.sun.tools.javac.api.JavacTool

**Comment by fengberd** [comment]
See the README.md please,you should to install the tools.jar


Best Regards,
FENGberd

**Comment by XFizzer** [comment]
I do have it installed

**Comment by fengberd** [comment]
I don't know,maybe you need launch it with JDK instead of JRE



Best Regards,
FENGberd
